- hosts: ec2
  gather_facts: no

  tasks:
  - name: install package
    package:
      name: httpd
      state: present
  - name: start and enable service
    service:
      name: httpd
      state: started
      enabled: yes
  - name: install php 
    command:  amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
  - name: add to group 
    group:
      name: www
      state: present
  - name: Add the user 'ec2-user'
    user:
      name: ec2-user
      groups: www
      append: yes
      
  - name: permissions 
    file:
      path: /var/www
      group: www
      mode: '2775'
      
  - name: set type permissions
    command: "{{item}}"
    with_items:
       - find /var/www -type d -exec sudo chmod 2775 {} +
       - find /var/www -type f -exec sudo chmod 0664 {} +  
  





